id: P006681
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3703
  title: རྒྱུད་བླ་མའི་མཆན་འགྲེལ་
  author: ''
  volumes:
    a9abc90924d548d0859bb3f31a28b72d:
      image_group_id: I1KG3738
      title: ''
      volume_number: 1
      total_pages: 156
